#!/bin/bash
pushd `dirname $0` > /dev/null
b=$(pwd -P)
popd > /dev/null

rm $HOME/.git-completion.bash && ln -s $b/git-completion.bash $HOME/.git-completion.bash
rm $HOME/.bashrc && ln -s $b/bashrc $HOME/.bashrc
rm $HOME/.inputrc && ln -s $b/bashrc $HOME/.inputrc
rm $HOME/.vimrc && ln -s $b/vi/vimrc $HOME/.vimrc
