"Line Numbers - yes.
:set number
"Specify syntax files.
:syntax enable
"Row/Column indicators.
:set ruler
"Highlight search terms.
:set hlsearch

"Tab stop = 2
:set ts=2
:set shiftwidth=2
"No tabs.
:set expandtab


"Begin autocommands
"Check to see if we already have defined these
:if !exists( "au_loaded" )
:  let au_loaded = 1

"Special syntax files
:  au BufNewFile,BufRead *.less     set filetype=less
:  au BufNewFile,BufRead *.json     set filetype=json
:  au BufNewFile,BufRead *.md       set filetype=md
:  au BufNewFile,BufRead *.mst      set filetype=mustache
:  au BufNewFile,BufRead *.mustache set filetype=mustache

"Highlight trailing whitespace, tabs, and long lines.
:  hi unwanted ctermbg=cyan guibg=cyan
:  au BufReadPost,InsertLeave * match unwanted /\s\+\%#\@<!$\|\t\|\%>80v.\+/

"Highlight the 80th column if available.
:  if exists( '+colorcolumn' )
:    hi colorcolumn ctermbg=Gray
:    set colorcolumn=80
:  endif

"Clear match buffer. Check version for old AWS instances at work.
:  if version >= 702
:    au BufWinLeave * call clearmatches()
:  endif

"End autocommands
:endif
